### ISSUE TITLE
주제 : 팀플 플래너 어플 개발

### ISSUE THREAD

**Issue by skdlfjl** [jjimini98/capstoneproject#1]
어플의 메리트는 우리가 매번 시간표를 보면서 회의 시간을 정할 수는 있지만 그걸 그냥 자동으로 해준다는것. 시간표를 캡처하여 어플에 올려주면 이미지 분석을 통해 합쳐진 시간표를 자동으로 만들어준다. 그냥 손으로 문 열면 되는데 자동문을 굳이 쓰는걸 생각해보면 됨
어플의 타겟은 주로 팀플을 많이하는 학생들

조건 : 이미 프로젝트의 주제가 정해져있음.

1. 프로젝트의 이름과 팀 원 명 작성 >> 여러가지 프로젝트를 관리하기 위함

2. 각 팀원의 시간표를 캡처하여 어플에 올려주면 각 팀원의 시간표를 합쳐서, 비어있는 자투리 시간까지 전부 표기해줌. >> 한눈에 팀원의 스케줄 파악 가능
이때 추가적인 일정 또한 표기할 수 있도록 한다

3. 프로젝트의 마감 기한 설정
Ex) 12주

4. 프로젝트 진행의 기본적인 순서를정한다
Ex) 수집 > 분석 > 설계 > 개발 > 테스트 > 결과 

5. 기본적인 순서 안에서 세부적인 계획을 우선순위에 맞게 각 단계에 작성
Ex) 수집
1. 데이터 크롤링
2. 데이터 전처리

----------------------------------------

어플은 이렇게 입력된 정보를 가지고 앞에서 만들었던 합쳐진 시간표의 비어있는 시간에 계획을 세워 보여준다. 각 단계별로 작성된 세부적인 계획들이 시간표에 들어가게 되는것.
캘린더 형태로 한눈에 알아보기 쉽게 나와있지만, 아래처럼 스케줄러 형태로도 볼 수 있다.

[ 화요일 6시~9시 : 데이터 크롤링 ]
[ 수요일 5시~7시 : 데이터 크롤링 ] - 크롤링 완료
[ 목요일 3시~6시 : 데이터 전처리 ]
[ 토요일 6시~9시 : 데이터 전처리 ] - 전처리 완료

이렇게 어플이 임의로 팀플 시간표를 짜줬다. 근데  수요일까지 크롤링을 마치지 못했다면?
>> 남아있는 목요일~일요일동안의 계획을 다시 짜서 보여준다.

**Comment by jjimini98** [comment]
https://velog.io/@vanang7/%EA%B5%AD%EB%AC%B8-%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4-OCR

**Comment by jjimini98** [comment]
https://niceman.tistory.com/155

**Comment by skdlfjl** [comment]
일단 해야하는것

1. 사진 불러오기 
 > 어플에서 사진을 여러장 올리기

2. 시간표 자르기
> 사진을 올렸을 때 프로그램으로 자를 수 있어야됨

3. 사진 크기조절
> 여러장의 사진을 같은 사이즈로 통일
