### ISSUE TITLE
파일 업로드 및 공유 방식에 대한 논의 

### ISSUE THREAD

**Issue by jjimini98** [jjimini98/capstoneproject#11]
## ⭐ 파일 업로드 및 공유 방식에 대한 논의 ⭐ 

_후,,, 일주일 중 3일을 파일 확인하는데 썼습니다..;;;;;_                    
   
지희님이 주신 파일을 받고 압축을 푸는데까지는 별 문제가 없지만, 진짜 문제는 그 파일을 andriod studio로 옮겨서 실행하는데서 발생했습니다.  

![image](https://user-images.githubusercontent.com/46179699/100917217-333d2880-351a-11eb-99d9-a37483747be9.png)
이런식으로 저 Unnamed 앞에 빨간색 X도 없어야하고 module도 제대로 있어야하는데 그렇지 않아서 계속 오류가 발생했습니다.
![image](https://user-images.githubusercontent.com/46179699/100916996-e8bbac00-3519-11eb-858b-d2fd7d604906.png)
위의 사진이 정상작동했을 때의 사진입니다.  
                       
구글링과 재설치를 반복한 끝에 제가 생각하는 이런 문제의 원인은 
**1. 파일의 경로의 차이
2. gradle 의 차이 
3. 업데이트 후 생기는 버전차이**    
라고 여겨집니다.            
                                     
안드로이드 스튜디오를 몇 달 간 써본 결과 업데이트의 속도가 빠르고 빈번합니다.; 그런 버전의 차이에서 오는 문제도 있고 두번째는 파일의 경로라고 해야하나,, ?지희님 컴퓨터의 프로젝트 위치와 제 컴퓨터 안에서의 프로젝트 위치가 다르기 때문에 gradle도 거기선 문제없이 bulid 가 되지만 여기서는 안되는 등 굉장히 변수가 많아 난감한 상황이 한 두 번이 아닙니다. 

도대체 어디서 생기는 문제인지 명확하게 알 수 가 없어서 좀 답답하긴 하네요...
그래서 파일을 보낼 때 압축해서 메일이나 채팅으로 보내는 방법 말고 다른 방법을 생각해서 하고 싶은데 어떻게 생각하세요?

git에서 브랜치를 새로 따서 하거나 아니면 다른 사이트에 업로드하거나 다양한 방식을 생각해봐야할 것 같습니다.

**Comment by jjimini98** [comment]
+) 추가내용 
인텔리제이도 안드로이드 앱 개발할 때 좋다고 해서(_훨씬 빠르다고 함_) 설치해보았는데 제가 설정을 이상하게 한건지 잘 안되어서 안드로이드 스튜디오로 계속 진행하려고 합니다.

**Comment by skdlfjl** [comment]
어짜피 브랜치 따서 올려야하니까 [브랜치로 올리는게](https://ksb0511.tistory.com/entry/%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C%EC%8A%A4%ED%8A%9C%EB%94%94%EC%98%A4-branch-%ED%8C%8C%EC%84%9C-Github%EC%97%90-%EC%98%AC%EB%A6%AC%EA%B8%B0) 나을 것 같아요. 근데 저번에 얘기해 보니까 저랑 지민님이랑 생각하고있는 merge기준이 조금 다른 것 같아서 기준을 맞춰야할 것 같습니다.

저는 일단 (제가 생각하기에)최종적으로 확정된 코드만 MR을 보냅니다. 그러면 상대방이 MR을 확인하고 수정할 부분이 있으면 댓글을 남기거나 따로 연락을 해서 코드를 수정하고, 만약 수정할 부분이 없다면 Merge합니다.
MR을 보내기 전까지는 브랜치만 따놓고, 그 브랜치에 수시로 commit해서 코드(혹은 데이터)들을 수정합니다. 브랜치에 올려두면 상대방도 git에서 브랜치에 들어가 데이터를 볼 수 있으니까요.

이게 맞는건지는 잘 모르겠는데 애초에 MR을 보내는 이유가 상대방의 코드 등을 확인하고 검증하기 위해서인데, 아직 정확히 검증되지 않은(최종적으로 사용하게 될지 아닐지 모르는?) 코드를 섣불리 merge해도 되는걸까요??
어플 개발 특성상 세세한 부분을 계속해서 수정해야 할텐데, 브랜치를 따서 바로 merge를 해버리면 이미 마스터브랜치에 올라간 것들은 그대로 남아버리는거 아닌가요..?? 으음..... 어렵다잉

**Comment by jjimini98** [comment]
어,, 근데 merge request 요청한 상태에서 수정할 부분을 수정해도 되나요? 그러면 다시 merge request를 해아하는 거 아닌가...? 싶은생각이 듭니다.                 
 계속 master에 merge 하는거랑 계속 commit 해서 한 번에  master로보내나 그게 그거같은데.. 저도 헷갈려서 한 번 다시 찾아보겠습니다. 
그러면 각자 branch에서 commit 하고 완료되었을때 MR하는걸로 알고 있을게요

**Comment by skdlfjl** [comment]
merge request 요청한 상태에서 수정 가능합니다, 수정하면 commit으로 올라갈거에요. python은 가능했는데 안드로이드 스튜디오는 잘 모르겠네요; 뭐 정 안되면 MR 닫고 새 MR 열면 되지 않을까요?

**Comment by jjimini98** [comment]
하긴,,, 뭐 방법이야 있으니까 일단 branch 내에서 수정하고 MR하는 방법으로 진행하겠습니다

**Comment by skdlfjl** [comment]
정리 : branch에서 다 정리하고 최종 코드와 최종 디렉토리를 master에다가 merge 한다. 그럼 branch의 내용이 master에 반영

이슈닫겠습니다
