### ISSUE TITLE
후보자 테이블 칼럼 값에 대한 논의 

### ISSUE THREAD

**Issue by jjimini98** [jjimini98/capstoneproject#13]
### **후보자 테이블 칼럼 값에 대한 논의** 

![image](https://user-images.githubusercontent.com/46179699/101064945-e7e94f80-35d7-11eb-9234-ec3d079acc84.png)

후보자의 정보가 들어가는 테이블에서  값이 어떻게 들어가는지 궁금해서 이슈 남깁니다.
그림에서 왼쪽처럼 토큰의 값이 달라질 때마다 새롭게 Key값을 주는지? 아니면 토큰의 값이 달라지는 것과 관련없이 Key값을 주는건지? 궁금합니다.

**Comment by jjimini98** [comment]
### **⚠️  같이 고려할 사항** 

저희가 DB로 사용하는 firebase는 NoSQL을 기반으로 하고 있어 우리가 데이터베이스 개론때 배웠던 테이블 형태가 아닌 **'딕셔너리' 형태입니다.**

**Comment by jjimini98** [comment]
NoSQL 개념을 어느정도 알아야 코드도 이해할 수 있을 것 같아서 NoSQL 공부한 내용 올려드립니다. 


[https://www.notion.so/growingarchive/NoSQL-8a0c1c62c7544c19a3919997f2bb068e](url)

**Comment by skdlfjl** [comment]
[딕셔너리](https://wikidocs.net/16)라면 인덱스를 사용하지 못하니까 전 게시물에서 작성한 DB 정의를 수정해야 할 것 같네요.. 수정해서 다시 올리겠습니다
