### ISSUE TITLE
[Firebase] 데이터 저장 문제 

### ISSUE THREAD

**Issue by jjimini98** [jjimini98/capstoneproject#15]
### [Firebase] 데이터 저장 문제 

![image](https://user-images.githubusercontent.com/46179699/101268887-f6886000-37ab-11eb-9458-bc59ca934cc1.png)

위 코드를 보시면, 제가 지금 하고 있는게 학번이 들어있는 list1을 for each문을 사용해서 list1에 있는 요소를 하나씩 가지고 와서 writeNewVoter()라고 제가 따로 정의해둔 함수에 넣어 Firebase에 저장하는 걸 하고 있습니다.

사실, 제가 생각했던 결과 저장은 
학번과 , 투표여부가 학번마다 각각 하나씩 나오기를 원했는데요 .                                                     
문제는 코드를 실행하고 확인을 해보면, 

![image](https://user-images.githubusercontent.com/46179699/101268999-e2912e00-37ac-11eb-8487-ed7a85918a62.png)

이렇게 이전 결과도 같이 나오는 이상한 결과가 생깁니다 . eclipse 에서도 실행해보고 결과를 직접 찍어보기도 했는데                 
eclipse에선 요소가 하나씩 나오게 되고 android 에서 결과를 print 하면 이전 요소도 겹치게 나오는 문제가 생깁니다..                   
코드 보시고 이상한 점 있으면 말해주세요.!

**Comment by skdlfjl** [comment]
1. 데이터가 최종적으로 저장되어야 하는 곳은 CreatActivity3 입니다. 일단 이론상으로는 CreatActivity, CreatActivity2는 그냥 데이터를 넘겨주는 액티비티이므로 추가적인 코드는 필요하지 않을 것 입니다. (하지만 제 코드가 틀렸을 수도 있으므로 수정이 필요할 수는 있습니다.)
2. 액션이 없으므로 첫번째 사진 속 코드의 토스트 메세지는 지워도 무방합니다.

이전 요소가 겹치게 나오는 문제는 제가 짠 액티비티 코드가 틀렸을 수 있습니다 다시한번 검토하고 수정할 부분 있으면 이슈 남기겠습니다

**Comment by skdlfjl** [comment]
> CreatActivity3의 코드입니다
![image](https://user-images.githubusercontent.com/71308174/101272707-031faf00-37d2-11eb-99bc-506e1f4270d8.png)
![image](https://user-images.githubusercontent.com/71308174/101272729-4f6aef00-37d2-11eb-8800-66b3d9060bb9.png)

만약 CreatActivity, CreatActivity2에서 list1, list2에 저장한 투표 참여학생 학번과, 후보자 이름 | 공약이 쌓여서 저장되었다면, 마지막 화면에서

20171478
20171478
20171489

로 결과가 나왔을 것입니다, CreatActivity3에서는 그냥 for문으로 (ArrayList)list1값을 꺼내서 찍어준 코드를 사용했으니까요
일단 CreatActivity에서 작성한 DB저장 코드를 3번액티비티로 옮겨서 다시 실행해 봐야 할 것 같습니다

**Comment by skdlfjl** [comment]
@jjimini98 아 그리고 token들을 먼저 DB에 저장한 뒤에 하는게 낫지 않을까요?  어짜피 token저장하는 DB는 한번 만들어두면 딱히 수정할 일이 없으니까요. (마지막 투표완료여부만 업데이트 되면서 값만 바뀝니다) 일단 token들 csv로 저장한거 보내드리겠습니다

**Comment by jjimini98** [comment]
@skdlfjl token csv로 만드신거 깃허브에 올려주세요!

**Comment by jjimini98** [comment]
> > CreatActivity3의 코드입니다
> 
> ![image](https://user-images.githubusercontent.com/71308174/101272707-031faf00-37d2-11eb-99bc-506e1f4270d8.png)
> ![image](https://user-images.githubusercontent.com/71308174/101272729-4f6aef00-37d2-11eb-8800-66b3d9060bb9.png)
> 
> 만약 CreatActivity, CreatActivity2에서 list1, list2에 저장한 투표 참여학생 학번과, 후보자 이름 | 공약이 쌓여서 저장되었다면, 마지막 화면에서
> 
> 20171478
> 20171478
> 20171489
> 
> 로 결과가 나왔을 것입니다, CreatActivity3에서는 그냥 for문으로 (ArrayList)list1값을 꺼내서 찍어준 코드를 사용했으니까요
> 일단 CreatActivity에서 작성한 DB저장 코드를 3번액티비티로 옮겨서 다시 실행해 봐야 할 것 같습니다

아까 CreatActivity에서 작성한 코드를 CreatActivity3 으로 옮겼는데 단순 이동에도 불구하고 제대로 작동하지  않는 문제가 있습니다;;; 코드 옮기고 다시 이슈 남길게요 😉

**Comment by skdlfjl** [comment]
제가 아직 putty랑 github랑 연동을 안해서뤼...ㅋ...... 집가서 연동하고 코드랑 같이 바로 올릴게요 일단 카톡으로 파일 보냈습니다ㅋㅋ

**Comment by jjimini98** [comment]
> @skdlfjl token csv로 만드신거 깃허브에 올려주세요!

제가 방금 firebase 브랜치에 올려놨습니다 ! 
경로 : capstoneproject/test/app/src/main/java/com/example/test/token.csv

**Comment by jjimini98** [comment]
## CreateActivity3에 코드이동, 변하지 않는 값의 저장.. 

> 아까 CreatActivity에서 작성한 코드를 CreatActivity3 으로 옮겼는데 단순 이동에도 불구하고 제대로 작동하지 않는 문제가 있습니다;;; 코드 옮기고 다시 이슈 남길게요 😉

아까 피드백 주신대로 CreatActivity3에 코드 옮겨서 재실행 해봤지만 결과는 같습니다.... 
![image](https://user-images.githubusercontent.com/46179699/101287322-ecf60b00-3832-11eb-8ac4-7471181b9cc1.png)

하아...오늘 꼭 해결하고 잘게요 화이팅... 🔥 🔥 🔥
