### ISSUE TITLE
[Android Studio] 안드로이드 스튜디오와 Github 연동 방법 

### ISSUE THREAD

**Issue by jjimini98** [jjimini98/capstoneproject#16]
https://m.blog.naver.com/beaqon/221278572578

생각보다 간단해서 공유해봅니다.  한 번 실행해봐연 
굳이 PuTTY로 안해도 되는듯..

**Comment by jjimini98** [comment]
https://neosla.tistory.com/47 


이런 방법도 있대요

**Comment by jjimini98** [comment]
❗ ❗  엄청난 발견 ❗ ❗ 

@skdlfjl 
PuTTY와 Filezilla 를 같이 쓰면 됩니다..
노트북의 파일은 filezilla로 업로드하고 PuTTY에서는 push 하고~!!!!

**Comment by skdlfjl** [comment]
연동 성공했습니다 감솨함돳~~
