### ISSUE TITLE
[Firebase] 데이터 저장 문제2 

### ISSUE THREAD

**Issue by jjimini98** [jjimini98/capstoneproject#17]
## [Firebase] 데이터 저장 문제2 

![image](https://user-images.githubusercontent.com/46179699/101290427-8fb78500-3845-11eb-801d-9f53073f788c.png)

제가 점점 바보가 되어가는거 같아요,,,, 🤮 
뭐가 문제지 대체,,,,위 사진은 안드로이드에서 학번을 입력했을 때 콘솔창에 입력되는 list1의 요소입니다. 
와,, 봐도 모르겠는데 혹시 힌트가 될 만한게 있을까요?

**Comment by skdlfjl** [comment]
괜찮아요 우리는 원래 바보팀이잖아요. 학번 3개 쳤을 때 그냥 3개만 중첩되는게 아니라 한가지가 또 중복되서 나오네요, 하다못해 그냥 단순히 중첩만 되서 나오는거면 마지막 인덱스만 가져와서 쓰면 되긴 할텐데... 더 생각해봐야 할 것 같습니다. 액티비티 코드 문제인지 다시 한번 확인해볼게요

**Comment by jjimini98** [comment]
마자여,, 우린 바보팀이긴 한데 팀이름이 바보지 우리가 진짜 바보는 아니였잖아요...?           
근데 진짜로 바보가 된거 같아요....

**Comment by skdlfjl** [comment]
데이터 저장문제 원인 찾았습니다, 역시 제 코드가 대차게 틀렸네요ㅋ 팀 이름이 바보팀인데 저만 바보인듯요; 진작에 이렇게 확인할걸 그랬습니다 말이 너무 길어질거같으니 이슈로 정리해서 올리겠습니다 재삼다~!!
