### ISSUE TITLE
[ 시간표 전처리 - 진행순서 ] 2020.10.06

### ISSUE THREAD

**Issue by skdlfjl** [jjimini98/capstoneproject#2]
시간표 전처리 과정입니다. 글은 수정될 수 있습니다

1. 사진 불러오기
> 어플에서 사진을 여러장 올렸을 때, 여러장의 사진들을 한번에 불러올 수 있어야 한다.

2. 시간표 자르기
> 사진을 올렸을 때 시간표만 잘라올 수 있어야 한다.

[Python과 OpenCV로 이미지 외곽 찾기, 이미지 자르기, 원하는 부분만 자동으로 잘라내기](https://youbidan.tistory.com/19)
[Windows에 OpenCV 설치하기 (by pip)](https://dejavuqa.tistory.com/228)
[anaconda에 opencv 설치하고 jupyter로 테스트](https://copycoding.tistory.com/142)

3. 잘라온 사진 크기조절
> 우리는 여러장의 사진을 한번에 받아 올 것이기 때문에, ML에 넣기 위해서는 사진을 같은 사이즈로 통일해야 한다.

**Comment by skdlfjl** [comment]
[안드로이드 앱 개발 튜토리얼(샘플만들기)](https://www.youtube.com/watch?v=Yhnvdx6FAQQ)

**Comment by jjimini98** [comment]
와우 멋지네여 읽어보겠습니다
