### ISSUE TITLE
[Firebase - 데이터 저장 문제 해결 + DB정의 수정 or Android코드수정] 20.12.08

### ISSUE THREAD

**Issue by skdlfjl** [jjimini98/capstoneproject#20]
아래는 CreatActivity3.java 코드중, textview에 찍어주는 부분의 코드입니다. 
```
        list1_size = list1.size();
        for(int i=0; i<list1_size; i++){
            tv_list1.setText((String) list1.get(i));
        }

        list2_size = list2.size();
        for(int i=0; i<list2_size; i++){
            tv_list2.setText((String) list2.get(i));
        }

// tv_list1, tv_list2는 기존에 있던 코드입니다
// tv_list3, tv_list4는 제가 확인을 위해 추가한 코드입니다

        tv_list3 = findViewById(R.id.tv_list3);   
        tv_list3.setText(""+list1_size);

        tv_list4 = findViewById(R.id.tv_list4);
        tv_list4.setText(""+list2_size);
```
학번입력하는 창 : '20171478', '20171468', '20171489'
후보자 입력하는 창 : '유지민 | 햄버거 돌릴게요', '이지희 | 공약없음'

위처럼 edit text에 입력을 하고 CreatActivity3.java이 실행된다면 결과는

**20171478
20171468
20171489**

**유지민 | 햄버거돌릴게요
이지희 | 공약없음**

**1**

**1**

이렇게 나옵니다
엥? 학번이랑 후보자 입력한건 잘 나왔는데 왜 list1, list2 사이즈가 1이지???

왜냐하면 **제가 list1에 저장한건 [ '20171478/n', '20171468/n', '20171489/n' ] 이게아니라
[  '20171478/n20171468/n20171489/n' ]** 이거이기 때문입니다ㅋ;... 아래 코드를 보면 왜 이렇게 저장된지 알 수 있습니다

아래는 CreatActivity.java 코드의 중간부분입니다. 하도 지겹게 봐서 어느부분인지는 알겠죠? 
```
ArrayList list1 = new ArrayList();
    private void displayContacts() {
        FileInputStream fis = null;
        BufferedInputStream bis = null;
        DataInputStream dis = null;

        try {
            fis = openFileInput(mFILENAME);
            bis = new BufferedInputStream(fis);
            dis = new DataInputStream(bis);

            String str = "";
            while (dis.available() > 0) {
                String studentID = dis.readUTF();

                str += studentID + "\n";

            }
            tv_display.setText(str);
            list1.add(str);

        } 
// .... 중략 ....
        }
    }
```
코드를 잘 보면 while반복문을 이용해 그냥 str변수에 쌓아주고있죠? 

그럼 결국 **최종적으로 반복문이 끝나면 str 변수에는 단순히 studentID가 \n 으로 구분되어있는 문자열 하나가 저장**됩니다
**그리고 그걸 그냥 list1에 add해줬으면 list1안에는 몇개의 문자열이 들어있을까요?**  한개가 들어있겠죠?? 저는 왕바보입니다

여기서 이제 우리는 두가지 선택을 할 수 있습니다
1. DB 정의를 수정한다 : [Firebase] 데이터 저장 문제[[Firebase] 데이터 저장 문제2](https://github.com/jjimini98/capstoneproject/issues/17)이슈에서 말했던 것 처럼 그냥 마지막 인덱스(인줄 알았던.. 실제로 리스트에 값은 하나뿐입니다)만 가져와서 쓰는 방법입니다. 근데 되게 번거롭습니다.  '20171478/n20171468/n20171489/n'를 /n 기준으로 나눠주는 중간 작업이 필요합니다. 그나저나 애초에 문자열 하나라서 ArrayList에 저장할 필요도 없겠네요; 쓰다보니 되게 별로인듯;
2. Android 코드를 수정한다 : 제가 걍 코드를 수정해서 제대로 list에 하나씩 제대로 저장하는 방법입니다

2번이 나은거같네요 걍 2번합시다 T T ㅋㅋ 재삼다 언넝 코드수정 해보겟슴다~!

**Comment by jjimini98** [comment]
어,, 그러면 잠시만 firebase에 자꾸 앞에꺼랑 겹쳐나오는 것도 같은 이유인가요?

**Comment by skdlfjl** [comment]
```
list1_size = list1.size();
for(int i=0; i<list1_size; i++){
     tv_list1.setText((String) list1.get(i)); 
}
```
그리고 이 코드는 textview(id : tv_list1)에 for문으로 하나씩 출력해서 찍어주는 코드가 아니었습니다 (헐~)
그냥 textview에 덮어씌워져서 결국 마지막 인덱스값만 찍혀요 (헐..) 저부분도 수정하겠습니다

**Comment by skdlfjl** [comment]
> 어,, 그러면 잠시만 firebase에 자꾸 앞에꺼랑 겹쳐나오는 것도 같은 이유인가요?

예,,,

**Comment by jjimini98** [comment]
아하 코드 잘못된 부분 찾으신게 대단하네여,,, 감사합니다

**Comment by skdlfjl** [comment]
코드 수정해서 풋쒸 했습니다~~ 어플로 잘 돌아가는지까지 확인했으니 이슈닫을게요 ~.~
