### ISSUE TITLE
[‼️Mission‼️] ~ 20.12.13(일)

### ISSUE THREAD

**Issue by skdlfjl** [jjimini98/capstoneproject#21]
> **유지민 (Firebase)**
- [x] value 리스트 형태로 저장하는 방법 터득
- [x] dict1 = {'key' : 0, 1 : ["302327vyztx", 0] , 2 : ["593937odxrs", 0], 3 : ["650244gwsvo", 0], 4 : ["224455ykfzd", 0], ... } 생성

> **이지희 (Android)**
- [x] next 버튼 클릭시 +1씩 count 되도록 코드구현 (CreatActivity2 -> CreatActivity3)
- [x] 투표기능 구현 (SubActivity2)
- [x] 후보자 이름이랑 공약 분리해서 저장하기 (성공하면 DB정의까지 수정하기)

딥러닝 시험 잘보세요 ~

**Comment by skdlfjl** [comment]
후보자 이름이랑 공약 분리해서 저장하는 코드 제 브랜치에 push해놨습니다. 
수정된 부분이 상당히 많으니 코드 보고 이해 안가면 이슈 남겨주세요

DB정의 수정은 좀 나중에 할게요 ㄱ-

**Comment by jjimini98** [comment]
WOW 😮  정말 들었던 것처럼 정리의 신이세요... 감사합니다

**Comment by jjimini98** [comment]
> > **유지민 (Firebase)**
> 
> * [ ]  value 리스트 형태로 저장하는 방법 터득
> * [ ]  dict1 = {1 : ["302327vyztx", 0] , 2 : ["593937odxrs", 0], 3 : ["650244gwsvo", 0], 4 : ["224455ykfzd", 0], ... } 생성
> 
> > **이지희 (Android)**
> 
> * [ ]  next 버튼 클릭시 +1씩 count 되도록 코드구현 (CreatActivity2 -> CreatActivity3)
> * [ ]  투표기능 구현 (SubActivity2)
> * [x]  후보자 이름이랑 공약 분리해서 저장하기 (성공하면 DB정의까지 수정하기)
> 
> 딥러닝 시험 잘보세요 ~

딥러닝 화이팅팅팅팅탱탱탱탱

**Comment by skdlfjl** [comment]
![image](https://user-images.githubusercontent.com/71308174/101495215-a546bf00-39ab-11eb-925c-ce02277af37d.png)

실수로 커밋 두번해서 ㄱ-... 수정된건 노란색으로 표시해둔거로 보세유

그리고 DB정의가 재금 많이 수정될 것 같습니다, 만약 위에 2가지 기간안에 끝나면 무조건 저한테 먼저 알려주세요 ~~

**Comment by skdlfjl** [comment]
dict1 = {1 : ["302327vyztx", 0] , 2 : ["593937odxrs", 0], 3 : ["650244gwsvo", 0], 4 : ["224455ykfzd", 0], ... }

이렇게 말고

dict1 = {**'key' : 0,** 1 : ["302327vyztx", 0] , 2 : ["593937odxrs", 0], 3 : ["650244gwsvo", 0], 4 : ["224455ykfzd", 0], ... }  

이렇게 구현해주세요,  이슈 수정해두겠습니다

**Comment by skdlfjl** [comment]
> > next 버튼 클릭시 +1씩 count 되도록 코드구현
> 
> **count는 누적되어야 하기 때문에 count된 숫자를 저장해둘곳이 필요합니다.**
> 
> dict1 = {1 : ["302327vyztx", 0] , 2 : ["593937odxrs", 0], 3 : ["650244gwsvo", 0], 4 : ["224455ykfzd", 0], ... }
> 
> 이렇게 말고
> 
> dict1 = {**'key' : 0,** 1 : ["302327vyztx", 0] , 2 : ["593937odxrs", 0], 3 : ["650244gwsvo", 0], 4 : ["224455ykfzd", 0], ... }
> 
> 이렇게 구현해주세요, 이슈 수정해두겠습니다

해당 글은 [[DB정의(1) - 기존 정의 수정]](https://github.com/jjimini98/capstoneproject/issues/23)에 관련되어있습니다.
[[DB정의(2) - pop사용]](https://github.com/jjimini98/capstoneproject/issues/22)까지 확인해주시고 둘중 편한거로 구현해주세요.
각각 장단점이 존재합니다!

**Comment by skdlfjl** [comment]
> 투표기능 구현 (SubActivity2) 참고 링크 
https://loveiskey.tistory.com/171 
https://mixup.tistory.com/36
