### ISSUE TITLE
[강제적인 투표 문제] 20.12.12

### ISSUE THREAD

**Issue by skdlfjl** [jjimini98/capstoneproject#26]
이 투표어플의 가장 큰 장점은 누가 누구에게 투표했는지 절대로 알 수 없다는 점입니다. (무조건 비밀보장)

근데 문제는 **한명이라도 투표를 완료하지 않으면 결과를 볼 수 없다**는 것입니다. 사실 이 어플로 투표를 하는 경우는 강제적으로 전원이 투표를 해야하는 경우겠지요. 한명이라도 투표를 안하면 결과가 안나오니까요..

그래서 제 생각에 가장 최선은 **특정 토큰을 통해 투표를 하지 않은 학생을 확인할 수 있는 액티비티를 추가함으로서, 아예 투표의 강제성을 극대화** 하는 것입니다. 한마디로 **CreatActivity3에서 token이 2개 부여**되는거죠. 한개는 선거참여명부에 등록된 학생이 투표를 할 수 있도록 하는 token (모든사람이 투표를 완료하면 투표 결과를 보여주는 페이지로 이동) 이건 선거참여명부에 전부 등록되어있는 학생들에게 전달되는 token입니다. 그리고 **나머지 한개는 투표개설자(투표 총 관리자) 전용 token입니다. 이 token을 통해, 투표를 아직 하지 않은 학생의 학번을 확인할 수 있는 것입니다.**

> 이때 투표개설자는, 투표 진행상황을 알 수는 없습니다. 단지 그냥 투표를 하지 않은 학생의 학번만 볼 수 있는 것입니다. 투표의 비밀원칙은 무조건 보장됩니다.  @jjimini98

_Originally posted by @skdlfjl in https://github.com/jjimini98/capstoneproject/issues/25#issuecomment-743718256_

**Comment by jjimini98** [comment]
오 새로운 기능이다.

**Comment by jjimini98** [comment]
저희 시간 제한도 있는건가요? 예를 들면 12월 15일이 투표날이다. 하면은 15일 9시부터 6시 이렇게 투표시간도 제한이 있는 건가요?

**Comment by skdlfjl** [comment]
> 저희 시간 제한도 있는건가요? 예를 들면 12월 15일이 투표날이다. 하면은 15일 9시부터 6시 이렇게 투표시간도 제한이 있는 건가요?

아뇨 없습니다. **투표완료 == 참여명단 전원 투표완료** 이게 현재까지 투표완료의 유일한 조건입니다.

**Comment by jjimini98** [comment]
> > 저희 시간 제한도 있는건가요? 예를 들면 12월 15일이 투표날이다. 하면은 15일 9시부터 6시 이렇게 투표시간도 제한이 있는 건가요?
> 
> 아뇨 없습니다. **투표완료 == 참여명단 전원 투표완료** 이게 현재까지 투표완료의 유일한 조건입니다.

그럼 저희는 투표를 완료할 때까진 무기한인건가요? 근데 보통 투표를 할 때 시간을 정해두지 않나요?                                             
그냥 투표개설자가 직접 닫으면 투표가 끝나는건가요?

**Comment by skdlfjl** [comment]
> > > 저희 시간 제한도 있는건가요? 예를 들면 12월 15일이 투표날이다. 하면은 15일 9시부터 6시 이렇게 투표시간도 제한이 있는 건가요?
> > 
> > 
> > 아뇨 없습니다. **투표완료 == 참여명단 전원 투표완료** 이게 현재까지 투표완료의 유일한 조건입니다.
> 
> 그럼 저희는 투표를 완료할 때까진 무기한인건가요? 근데 보통 투표를 할 때 시간을 정해두지 않나요?
> 그냥 투표개설자가 직접 닫으면 투표가 끝나는건가요?

아뇨 그냥 투표완료의 기준은 무조건 참여명단이 전원 투표를 완료해야만 투표가 끝납니다. 다른 조건은 전혀 없습니다. 투표개설자가 닫을수도 없습니다. 제가 쓴대로 진행한다면 투표개설자가 할 수 있는일은 투표개설과 참여명단에게 token전달, 개인 token으로 참여명단에 있는 사람들 중, 투표에 참여하지 않은사람의 학번을 볼 수 있는일이 전부입니다

**Comment by skdlfjl** [comment]
## 변경사항 
투표 완료기준 : 투표 참여명단에 있는 학생들의 80%가 투표 완료했을 시 투표완료. (소숫점은 버림)
> 유지민

1. 투표개설자용 token을 저장해둘 dict 추가, 형태는 dict1과 동일함
dict를 추가하지 않으려면 "key"를 2개로 늘려버리면 됨 

> 이지희

1. token 다시생성 (100000개 생성해서 반은 dict1, 반은 투표개설자용 token을 저장해둘 dict에 사용)
2. 참여명단에 있는 사람들 중, 투표에 참여하지 않은 학생들의 학번을 확인할 수 있는 액티비티 생성
3. CreatActivity3에 찍어서 보여주는 token개수 두개로 늘려야됨
