### ISSUE TITLE
주제 수정 및 앞으로의 계획

### ISSUE THREAD

**Issue by jjimini98** [jjimini98/capstoneproject#4]
### **주제 : 선거프로그램 만들기**

프로젝트 개요 :  코로나 19로 인해 학교의 풍경이 바뀌었다. 이제는 대면 수업이 아닌 비대면 수업으로 진행이 되고 비대면으로 진행되는 다양한 대외활동들과 웨비나 등 우리 일상이 변화하고 있다. 학과 또는 학교를 대표하는 과대표, 학회장, 학생회장 등은 학생들이 직접 투표를 통해 뽑힌다. 물론 전자투표, 카카오톡의 투표 기능을 이용할 수 있지만,  선거의 기본원칙인 익명의 원칙 비밀보장의 원칙이 잘 지켜진다고 보장할 수 없다. 따라서 우리는 익명,비밀보장의 원칙이 지켜지면서 비대면 투표이지만 더 공정한 선거프로그램을 만들면 어떨까하는 생각에서 이번 프로젝트가 출발했다.

#### 앱 내 기본 내용
1.  input으로 학번받기

2. 선거인 명부와 비교 (,으로 나뉘어진 학번으로 구성된 txt 파일)
2-1 . 있으면 투표할 수 있도록 후보명단을 보여준다.(후보 명단에는 기권항목도 추가)
2-2.  없다면 그냥 프로그램 종료

3. 후보명단에서 input으로 번호를 입력받는다.
3-1.  번호가 있으면 그 번호에 득표수 +1 을 한다.
3-2 . 번호가 없거나 이상한 문자열이 들어오면 기권표로 처리한다.

4. 투표가 끝나면 최종합계 비교 -> 제일 득표수가 많은 사람이 당선되게 된다.

#### 우리가 해결해야하는 추가 문제
1. 보안문제
2. 어떻게 새로운 사람이 계속해서 들어올 때 득표수를 유지하면서 계속 더할 수 있는지?
3. 앱 구현 방식

#### 예상계획
9주차- 10주차 : 앱의 기본 내용 구성 
11주차- 13주차 : 앱 구현 방식 
14주차-  15주차: 보안 문제 해결과 시연

**Comment by skdlfjl** [comment]
0. 카카오톡 투표기능과의 차별점? 결과함을 투표 기간내에 아무도 못 보게 하는 것 외에 또 무엇이 있는가 생각해봐야함.
1. 투표 진행자는 결국 스스로가 투표를 개설해야됨. 따라서 투표를 진행하는 사람이 선거 명부, 후보 명단, 후보의 공약을 전부 작성해야하는 상황 발생.
2. 투표를 마치는 기준은 무엇인가? (선거 명부에 들어있는 모든 학생이 선거를 마치면 자동으로 종료? 아니면 투표 진행자가 전체 투표 수를 확인하여 모든 사람이 참여한것을 확인 후 중단?)
3. 앱 자체를 일회성 앱(로그인이 필요없고 아무나 참여 가능한 앱)으로 생각한다면 선거명부에 들어가있는 학생들은 어떻게 그 앱에 접속할 수 있는가?
4-(1). 보안문제1 : 타과생, 타학교가 특정 과 투표 프로그램에 참여해서는 안됨.
4-(2). 보안문제2 : 본인인증 문제. (악의를 가지고 특정 학생의 투표를 막기위해 타 학생의 학번을 사용하는 문제발생 가능성 있음)


### 에 대한 이지희의 개인적인 생각 (참고만 하세요)
어플을 사용하려는 a과, b과, c과가 있다고 가정
각 학과의 투표진행자는 각자 핸드폰으로 투표를 개설한다. (진행자는 선거명부, 후보명단, 후보의 공약 등을 전부 작성해야됨)
투표 개설을 완료하면 투표진행자는 각 학과의 투표에 대한 토큰(비밀번호?)을 얻는다.
각 학과의 투표진행자는 선거명부에 있는 학생들에게 토큰을 전달한다.
학생들은 토큰을 어플에 입력하여 각 학과의 투표진행자가 개설한 투표를 진행할 수 있음.
>> 이런 방식이라면 3과 4-(1)문제를 해결 가능할 것이라 생각됨.
>> 집중적으로 생각해 봐야 할 문제는 4-(2) 인 것 같습니다.

**Comment by skdlfjl** [comment]
지금까지 많은 변경사항이 있었으므로 이슈 닫고 다시 정리해서 올리겠습니다.

**Comment by jjimini98** [comment]
네
